export const MAIN_PAGE_NASA_ITEMS_REQUEST = 'MAIN_PAGE_NASA_ITEMS_REQUEST';
export const MAIN_PAGE_NASA_ITEMS_SUCCESS = 'MAIN_PAGE_NASA_ITEMS_SUCCESS';
export const MAIN_PAGE_NASA_ITEMS_ERROR = 'MAIN_PAGE_NASA_ITEMS_ERROR';

export const MAIN_PAGE_NASA_IMAGE_OF_DAY_REQUEST = 'MAIN_PAGE_NASA_IMAGE_OF_DAY_REQUEST';
export const MAIN_PAGE_NASA_IMAGE_OF_DAY_SUCCESS = 'MAIN_PAGE_NASA_IMAGE_OF_DAY_SUCCESS';
export const MAIN_PAGE_NASA_IMAGE_OF_DAY_ERROR = 'MAIN_PAGE_NASA_IMAGE_OF_DAY_ERROR';

export const MERCURY_PAGE_NASA_IMAGE_OF_DAY_REQUEST = 'MERCURY_PAGE_NASA_IMAGE_OF_DAY_REQUEST';
export const MERCURY_PAGE_NASA_IMAGE_OF_DAY_SUCCESS = 'MERCURY_PAGE_NASA_IMAGE_OF_DAY_SUCCESS';
export const MERCURY_PAGE_NASA_IMAGE_OF_DAY_ERROR = 'MERCURY_PAGE_NASA_IMAGE_OF_DAY_ERROR';

export const VENUS_PAGE_NASA_IMAGE_OF_DAY_REQUEST = 'VENUS_PAGE_NASA_IMAGE_OF_DAY_REQUEST';
export const VENUS_PAGE_NASA_IMAGE_OF_DAY_SUCCESS = 'VENUS_PAGE_NASA_IMAGE_OF_DAY_SUCCESS';
export const VENUS_PAGE_NASA_IMAGE_OF_DAY_ERROR = 'VENUS_PAGE_NASA_IMAGE_OF_DAY_ERROR';

export const EARTH_PAGE_NASA_IMAGE_OF_DAY_REQUEST = 'EARTH_PAGE_NASA_IMAGE_OF_DAY_REQUEST';
export const EARTH_PAGE_NASA_IMAGE_OF_DAY_SUCCESS = 'EARTH_PAGE_NASA_IMAGE_OF_DAY_SUCCESS';
export const EARTH_PAGE_NASA_IMAGE_OF_DAY_ERROR = 'EARTH_PAGE_NASA_IMAGE_OF_DAY_ERROR';

export const MARS_PAGE_NASA_IMAGE_OF_DAY_REQUEST = 'MARS_PAGE_NASA_IMAGE_OF_DAY_REQUEST';
export const MARS_PAGE_NASA_IMAGE_OF_DAY_SUCCESS = 'MARS_PAGE_NASA_IMAGE_OF_DAY_SUCCESS';
export const MARS_PAGE_NASA_IMAGE_OF_DAY_ERROR = 'MARS_PAGE_NASA_IMAGE_OF_DAY_ERROR';

export const JUPITER_PAGE_NASA_IMAGE_OF_DAY_REQUEST = 'JUPITER_PAGE_NASA_IMAGE_OF_DAY_REQUEST';
export const JUPITER_PAGE_NASA_IMAGE_OF_DAY_SUCCESS = 'JUPITER_PAGE_NASA_IMAGE_OF_DAY_SUCCESS';
export const JUPITER_PAGE_NASA_IMAGE_OF_DAY_ERROR = 'JUPITER_PAGE_NASA_IMAGE_OF_DAY_ERROR';

export const SATURN_PAGE_NASA_IMAGE_OF_DAY_REQUEST = 'SATURN_PAGE_NASA_IMAGE_OF_DAY_REQUEST';
export const SATURN_PAGE_NASA_IMAGE_OF_DAY_SUCCESS = 'SATURN_PAGE_NASA_IMAGE_OF_DAY_SUCCESS';
export const SATURN_PAGE_NASA_IMAGE_OF_DAY_ERROR = 'SATURN_PAGE_NASA_IMAGE_OF_DAY_ERROR';

export const URANUS_PAGE_NASA_IMAGE_OF_DAY_REQUEST = 'URANUS_PAGE_NASA_IMAGE_OF_DAY_REQUEST';
export const URANUS_PAGE_NASA_IMAGE_OF_DAY_SUCCESS = 'URANUS_PAGE_NASA_IMAGE_OF_DAY_SUCCESS';
export const URANUS_PAGE_NASA_IMAGE_OF_DAY_ERROR = 'URANUS_PAGE_NASA_IMAGE_OF_DAY_ERROR';

export const NEPTUNE_PAGE_NASA_IMAGE_OF_DAY_REQUEST = 'NEPTUNE_PAGE_NASA_IMAGE_OF_DAY_REQUEST';
export const NEPTUNE_PAGE_NASA_IMAGE_OF_DAY_SUCCESS = 'NEPTUNE_PAGE_NASA_IMAGE_OF_DAY_SUCCESS';
export const NEPTUNE_PAGE_NASA_IMAGE_OF_DAY_ERROR = 'NEPTUNE_PAGE_NASA_IMAGE_OF_DAY_ERROR';

export const PLUTO_PAGE_NASA_IMAGE_OF_DAY_REQUEST = 'PLUTO_PAGE_NASA_IMAGE_OF_DAY_REQUEST';
export const PLUTO_PAGE_NASA_IMAGE_OF_DAY_SUCCESS = 'PLUTO_PAGE_NASA_IMAGE_OF_DAY_SUCCESS';
export const PLUTO_PAGE_NASA_IMAGE_OF_DAY_ERROR = 'PLUTO_PAGE_NASA_IMAGE_OF_DAY_ERROR';

export const MOON_PAGE_NASA_IMAGE_OF_DAY_REQUEST = 'MOON_PAGE_NASA_IMAGE_OF_DAY_REQUEST';
export const MOON_PAGE_NASA_IMAGE_OF_DAY_SUCCESS = 'MOON_PAGE_NASA_IMAGE_OF_DAY_SUCCESS';
export const MOON_PAGE_NASA_IMAGE_OF_DAY_ERROR = 'MOON_PAGE_NASA_IMAGE_OF_DAY_ERROR';
