export const MERCURY_PAGE_NASA_REQUEST = 'MERCURY_PAGE_NASA_REQUEST';
export const MERCURY_PAGE_NASA_SUCCESS = 'MERCURY_PAGE_NASA_SUCCESS';
export const MERCURY_PAGE_NASA_ERROR = 'MERCURY_PAGE_NASA_ERROR';

export const VENUS_PAGE_NASA_REQUEST = 'VENUS_PAGE_NASA_REQUEST';
export const VENUS_PAGE_NASA_SUCCESS = 'VENUS_PAGE_NASA_SUCCESS';
export const VENUS_PAGE_NASA_ERROR = 'VENUS_PAGE_NASA_ERROR';

export const EARTH_PAGE_NASA_REQUEST = 'EARTH_PAGE_NASA_REQUEST';
export const EARTH_PAGE_NASA_SUCCESS = 'EARTH_PAGE_NASA_SUCCESS';
export const EARTH_PAGE_NASA_ERROR = 'EARTH_PAGE_NASA_ERROR';

export const MARS_PAGE_NASA_REQUEST = 'MARS_PAGE_NASA_REQUEST';
export const MARS_PAGE_NASA_SUCCESS = 'MARS_PAGE_NASA_SUCCESS';
export const MARS_PAGE_NASA_ERROR = 'MARS_PAGE_NASA_ERROR';

export const JUPITER_PAGE_NASA_REQUEST = 'JUPITER_PAGE_NASA_REQUEST';
export const JUPITER_PAGE_NASA_SUCCESS = 'JUPITER_PAGE_NASA_SUCCESS';
export const JUPITER_PAGE_NASA_ERROR = 'JUPITER_PAGE_NASA_ERROR';

export const SATURN_PAGE_NASA_REQUEST = 'SATURN_PAGE_NASA_REQUEST';
export const SATURN_PAGE_NASA_SUCCESS = 'SATURN_PAGE_NASA_SUCCESS';
export const SATURN_PAGE_NASA_ERROR = 'SATURN_PAGE_NASA_ERROR';

export const URANUS_PAGE_NASA_REQUEST = 'URANUS_PAGE_NASA_REQUEST';
export const URANUS_PAGE_NASA_SUCCESS = 'URANUS_PAGE_NASA_SUCCESS';
export const URANUS_PAGE_NASA_ERROR = 'URANUS_PAGE_NASA_ERROR';

export const NEPTUNE_PAGE_NASA_REQUEST = 'NEPTUNE_PAGE_NASA_REQUEST';
export const NEPTUNE_PAGE_NASA_SUCCESS = 'NEPTUNE_PAGE_NASA_SUCCESS';
export const NEPTUNE_PAGE_NASA_ERROR = 'NEPTUNE_PAGE_NASA_ERROR';

export const PLUTO_PAGE_NASA_REQUEST = 'PLUTO_PAGE_NASA_REQUEST';
export const PLUTO_PAGE_NASA_SUCCESS = 'PLUTO_PAGE_NASA_SUCCESS';
export const PLUTO_PAGE_NASA_ERROR = 'PLUTO_PAGE_NASA_ERROR';

export const MOON_PAGE_NASA_REQUEST = 'MOON_PAGE_NASA_REQUEST';
export const MOON_PAGE_NASA_SUCCESS = 'MOON_PAGE_NASA_SUCCESS';
export const MOON_PAGE_NASA_ERROR = 'MOON_PAGE_NASA_ERROR';
